# Generated by Django 3.2.9 on 2022-03-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesalon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Date_Time',
            field=models.DateTimeField(auto_now_add=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
