# Generated by Django 3.2.9 on 2022-03-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesalon', '0002_auto_20220322_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Date_Time',
        ),
        migrations.AddField(
            model_name='customer',
            name='DateTime',
            field=models.DateTimeField(default='2022-03-29 22:25'),
        ),
    ]
