# Generated by Django 3.2.9 on 2022-09-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesalon', '0006_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('password1', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Customer',
            new_name='Appoinments',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
