# Generated by Django 3.2.9 on 2023-01-15 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesalon', '0007_auto_20220911_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connections',
        ),
    ]
